app/main/routes.py
from flask import (render_template, request, redirect, Blueprint,
                   session, url_for, flash, Markup,Request,
                   jsonify, send_file)
# from app import tasks
from .forms import (SvgForm, PickCounty, ExperimentForm,
                    BusinessForm, CustomBusinessForm,
                    CheckboxGridForm, GradeForm, WorkReportForm,
                    ChannelListForm, ExpForm, StateForm, DateTimeForm,
                    SimpleDateForm, CheckBoxHideForm)
from app import tables
from app.main.utils import do_plot, table_sorter
import pandas as pd
import logging
from datetime import datetime

from functools import partial
from .utils import Item, SubItem

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


formatter = logging.Formatter('%(asctime)s:%(name)s:%(message)s')

''' Make the file handler to deal with logging to file '''
file_handler = logging.FileHandler('logs/experiment_routes.log')
file_handler.setFormatter(formatter)

stream_handler = logging.StreamHandler() # level already set at debug from logger.setLevel() above

stream_handler.setFormatter(formatter)

logger.addHandler(stream_handler)
logger.addHandler(file_handler)

main = Blueprint('main',__name__)

from app import cel

@main.route("/") 
@main.route("/home") 
def home(): 
    form = SvgForm()
    return render_template('home.html',form=form)

@main.route("/demo")
def demo():
    
    return render_template('demo.html',)


@main.route("/test_focus")
def test_focus():
    column_name = "test_input"
    return render_template('test_focus.html',column_name=column_name)

@main.route('/process/<name>')
def process(name):
    tasks.reverse.delay(name) # starts celery process
    return 'I sent an async request'

@main.route('/pick_county/', methods=['GET', 'POST'])
def pick_county():
    form = PickCounty()
    states = db.State().fetch('state')
    form.state.choices = [(state,state) for state in states]
    counties = db.County().fetch('county')
    form.county.choices = [(county,county) for county in counties]
       
    if form.validate_on_submit() and request.form['form_name'] == 'PickCounty':
        # code to process form
        flash('state: %s, county: %s' % (form.state.data, form.county.data))
    return render_template('pick_county.html', form=form)

@main.route('/_get_counties/')
def _get_counties():
    state = request.args.get('state', '01', type=str)
    counties = (db.County & f'state="{state}"').fetch('county')
    counties_4json = [(county,county) for county in counties]
    print(counties_4json)
    return jsonify(counties_4json)

# @celery.task(name='celery_example.reverse') # if you don't put the name it infers the name for you and sometimes the name is not quite right
# def reverse(name):
#   return name[::-1]

@main.route('/state_county_js')
def state_county_js():
    return render_template("js/state_county.js")


@main.route("/test_vert_layout") 
def test_vert_layout(): 
    test_data = [{'username':'user1','age':20,'sex':'F'},
                 {'username':'user2','age':22,'sex':'M'},
                 {'username':'user3','age':30,'sex':'F'}]
    table = tables.TestTable(test_data)
    return render_template('test_vertlayout.html',table=table)


@main.route("/test_dynamic_form") 
def test_dynamic_form(): 

    return render_template('dynamic_form.html')    


@main.route("/checkbox_action") 
def checkbox_action(): 

    return render_template('checkbox_action.html')  

@main.route("/dynamic_samples") 
def dynamic_samples(): 
    form = ExperimentForm()
    return render_template('dynamic_samples.html',form=form) 

@main.route('/test_fieldlist', methods=['post','get'])
def test_fieldlist():
    form = BusinessForm()
    if form.validate_on_submit():
        results = []
        for idx, data in enumerate(form.hours.data):
            results.append('{day}: [{open}]:[{close}]'.format(
                day=calendar.day_name[idx],
                open=data["opening"],
                close=data["closing"],
                )
            )
        return render_template('results.html', results=results)
    # print(form.errors)
    hour1_dict = {'opening':'9am','closing':'5pm'}
    hour2_dict = {'opening':'10am','closing':'6pm'}
    hour_dict_list = [hour1_dict,hour2_dict]
    # while len(form.hours) > 0:
    #     form.hours.pop_entry()
    for ii in range(len(hour_dict_list)):
        form.hours.append_entry(hour_dict_list[ii])
    # form.name.data = "Test"
    return render_template('test_fieldlist.html', form=form)

@main.route("/checkbox_getjson") 
def checkbox_getjson(): 
    form = BusinessForm()
    return render_template('checkbox_getjson.html',form=form)

@main.route('/_render_form_fields/')
def _render_form_fields():
    nsamples = request.args.get('nsamples', '1', type=int)
    form = request.args.get('form',type=CustomBusinessForm)
    hour1_dict = {'opening':'9am','closing':'5pm'}
    hour2_dict = {'opening':'10am','closing':'6pm'}
    hour_dict_list = [hour1_dict,hour2_dict]
    print(nsamples)
    print(form)
    for ii in range(len(hour_dict_list)):
        form.hours.append_entry(hour_dict_list[ii])
    # print("in _render_forms()")
    
@main.route('/_generate_form_data/')
def _generate_form_data():
    nsamples = request.args.get('nsamples', '1', type=int)

    data = []
    for ii in range(nsamples):
        hour_dict = {'opening':'%i'%ii,'closing':'5pm','day':ii+1}        
        data.append(hour_dict)
    
    return jsonify(data)

@main.route("/checkbox_getjson_flask",methods=['GET','POST']) 
def checkbox_getjson_flask(): 
    form = CustomBusinessForm()
    if form.validate_on_submit:
        print(form.data)
    return render_template('checkbox_getjson_flask.html',form=form)

@main.route("/checkbox_grid_demo",methods=['GET','POST']) 
def checkbox_grid_demo(): 
    mydata = [{'channel':488,'registration':{'name':'reg_488','value':'reg_488'},
    'injection_detection':{'name':'inj_488','value':'inj_488'}},
              {'channel':555,'registration':{'name':'reg_555','value':'reg_555'},
              'injection_detection':{'name':'inj_555','value':'inj_555'}}]

    tab = tables.CheckBoxTable(mydata)
    return render_template('checkbox_grid_demo.html',table=tab)

@main.route("/checkbox_table_demo",methods=['GET','POST']) 
def checkbox_table_demo(): 
    if request.method == 'GET':
        # form_days = db.session.query(Work_Time).filter_by(user_id=current_user.id).all()
        form_days = [{'index':'0','start_time':'9am','end_time':'10pm'}]
        form = WorkReportForm(days=form_days)
    if request.method == 'POST':
        
        form = WorkReportForm(request.form)
        print(form.data)
        days = []
        # for day in form.days:
        #     print(day.index.data)
            # Work_Time(id = day.index.data,\
            #           user=current_user,\
            #           date=day.date.data,\
            #           start_time=day.start_time.data,\
            #           end_time=day.end_time.data)
    return render_template('checkbox_table_demo.html',form=form)    


@main.route("/channel_table_demo",methods=['GET','POST']) 
def channel_table_demo(): 
    form = ChannelListForm(request.form)

    if request.method == 'GET':
        print("get request")
        # channel_data = [{'channel':'488'},{'channel':'555'},
        # {'channel':'647'},{'channel':'790'}]
        # while len(form.channels) > 0:
        #     form.channels.pop_entry()
        # for ii in range(4):
        #     form.channels.append_entry(channel_data[ii])
        # print(form.data)
    elif request.method == 'POST':
        print("post request")
        print(form.data)
    return render_template('channel_table_demo.html',form=form)     


@main.route("/table_swapper",methods=['GET']) 
def table_swapper(): 
    test_data = [{'username':'user1','age':20,'sex':'F'},
                 {'username':'user2','age':22,'sex':'M'},
                 {'username':'user3','age':30,'sex':'F'}]
    table = tables.TestTable(test_data)
    table.table_id = 'mytable'
    return render_template('table_swapper.html',table=table)       


@main.route("/table_swapper_v2",methods=['GET']) 
def table_swapper_v2(): 
    test_data = [{'username':'user1','age':20,'sex':'F'},
                 {'username':'user2','age':22,'sex':'M'},
                 {'username':'user3','age':30,'sex':'F'}]
    table1 = tables.TestTable(test_data)
    table1.table_id = 'table1'
    table2 = tables.TestTable(test_data)
    table2.table_id = 'table2'
    return render_template('table_swapper_v2.html',table1=table1,table2=table2)   




@main.route("/table_swapper_v3",methods=['GET']) 
def table_swapper_v3(): 
    test_data = [{'username':'user1','age':20,'sex':'F'},
                 {'username':'user2','age':22,'sex':'M'},
                 {'username':'user3','age':30,'sex':'F'}]
    table1 = tables.TestTable(test_data)
    table1.table_id = 'vertical'
    table2 = tables.TestTable(test_data)
    table2.table_id = 'horizontal1'
    return render_template('table_swapper_v3.html',table1=table1,table2=table2)   

@main.route("/new_exp/",methods=['GET','POST']) 
def new_exp(): 
    # custom_clearing = request.args.get('custom_clearing',0)
    form = ExpForm(request.form)
    custom_clearing=None
    if form.validate_on_submit():
        print("validated")
        if form.custom_clearing_submit.data == True:
            custom_clearing = 1
            for ii in range(form.number_of_samples.data):
                form.clearing_samples.append_entry()
        elif form.uniform_clearing_submit.data == True:
            custom_clearing = 0 
            form.clearing_samples.append_entry()
        

        # redirect_url = '%s?custom_clearing=1' % url_for('main.new_exp')
        # return redirect(redirect_url)
    else:
        print(form.errors)
    if 'column_name' not in locals():
        column_name = ''
    print("custom_clearing =", custom_clearing)

app/templates/channel_table_demo.html
{% extends "layout.html" %}
    {% block content %}
    {% set channel_list = ['488','555','647','790'] %}
               <form method="post">
            <table>
                <tr>
                    <th>channel</th>
                    <th>Registration</th>
                    <th>Injection detection</th>
                    <th>Probe detection</th>
                    <th>Cell detection</th>

                </tr>
                <tr>   
                    <td>488</td>
                    <td>{{form.channel1_registration}}</td>
                    <td>{{form.channel1_injection_detection}}</td>
                    <td>{{form.channel1_probe_detection}}</td>
                    <td>{{form.channel1_cell_detection}}</td>

                </tr>
                <tr>   
                    <td>555</td>
                    <td>{{form.channel2_registration}}</td>
                    <td>{{form.channel2_injection_detection}}</td>
                    <td>{{form.channel2_probe_detection}}</td>
                    <td>{{form.channel2_cell_detection}}</td>

                </tr>
            </table>
            <div class="form-group">
                {{ form.submit(class="btn btn-success mt-2") }}
            </div>
        </form>

    {% endblock content %}

app/templates/custom_table_cols.html
{% extends "layout.html" %}
	{% block content %}
		{{ table }}
	{% endblock content %}

app/templates/demo.html
{% extends "layout.html" %}
	{% block content %}

<table>
<thead><tr><th></th><th>Name</th></tr></thead>
<tbody>
<tr><td></td><td>name1</td></tr>
<tr><td></td><td>name2</td></tr>
<tr><td></td><td>name3</td></tr>
</tbody>
</table>

{% endblock content %}

app/templates/dynamic_samples.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" id="myform">
		{{ form.hidden_tag() }}
			<fieldset class="form-group" id="myfieldset">
				<div class="form-group">
					{% if form.title.flags.required %}*{% endif %}

					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{% if form.number_of_samples.flags.required %}*{% endif %}

					{{ form.number_of_samples.label(class="form-control-label") }}
					{% if form.number_of_samples.errors %}
						{{ form.number_of_samples(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.number_of_samples.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.number_of_samples(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.customize_sample_names(class="form-check-input mb-4") }}
					{{ form.customize_sample_names.label(class="form-check-label mb-4") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-info mt-4") }}	            
			</div>
			
		</form>

 <script type="text/javascript">

       $("#customize_checkbox").click(function() {
    // this function will get executed every time the #mybox element is clicked (or tab-spacebar changed)
    if($(this).is(":checked")) // "this" refers to the element that fired the event
    {
        var num = Number($('#nsamples').val());
        // console.log(num);
        // console.log(typeof(num));
        var text = "";
        // alert('mybox is checked');
       for (i = 0; i < num; i++) {
          text += '<div><input type="text" name="name[]" class="form-control" placeholder="Enter Sample Name"/></div>';
        }
        $('#myfieldset').append(text);
    }
});
    </script>

{% endblock content %}
	

app/templates/dynamic_table.html
{% extends "layout.html" %}
	{% block content %}
		{{ table }}
	{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
	{% block content %}
		Welcome home
	{% endblock content %}

app/templates/js_fill_datetime_form_field.html
{% extends "layout.html" %}
	{% block content %}

	<form method="post" action="">
		{{ form.datetime1.label}}
	    {{ form.datetime1()}}
		{% set mykey = 'datetime1' %}
			<button  class="btn btn-primary" onclick="autoFill(key='{{mykey}}')">Click me</button>
		{{ form.datetime2.label}}
	    {{ form.datetime2()}}
	    {{ form.hidden_tag() }}
	    
	</form>
	

	<script>
	function autoFill(key) {
	console.log("Made it into the function")
	var d = new Date();
	var day = d.getDate();
	var month = d.getMonth()
	var year = d.getFullYear()
	var hour = d.getHours()
	var minute = d.getMinutes()
	var second = d.getSeconds()
	var s = year + '-' + month + '-' + day + 'T' + hour + ':' + minute + ':' + second;
	
	console.log(s);
	document.getElementById(key).value = s;
	}
</script>
	{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">
		<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

		<title>Flask Demo</title>
</head>
<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
				<!-- Navbar Left Side -->

					<a class="navbar-brand mr-4" href="/">Flask Demo</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarToggle">
						
							<div class="navbar-nav mr-auto">
								<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
							</div>
						
					</div>
				</div>
			</nav>
		</header>
	<main role="main" class="container">
				  {% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
					  {% for category, message in messages %}
						<div class="alert alert-{{ category }}">
						  {{ message }}
						</div>
					  {% endfor %}
					{% endif %}
				  {% endwith %}
				{% block content %}{% endblock %}
	</main>
	


		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/pick_county.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<div class="form-group">
					{{ form.state.label }}
					{{ form.state(class="form-control form-control-sm") }}
				</div>
				<div class="form-group">
					{{ form.county.label }}
					{{ form.county(class="form-control form-control-sm") }}
				</div>
				<div class="form-group">
					{{ form.submit(class="btn btn-info mt-4") }}	            
				</div>
			</fieldset>
		</form>

<script src="{{ url_for('main.state_county_js') }}"></script>

{% endblock content %}
	

app/templates/plot.html
{% extends "layout.html" %}
	{% block content %}
		<h1> Your plot: </h1>
		<img src="{{ url_for('main.correlation_matrix') }}" />
		How does your plot look?
	{% endblock content %}

app/templates/tablewidth.html
{% extends "layout.html" %}

{% block content %}
	{{ table }}
{% endblock content %}

app/templates/test_customrows.html
{% extends "layout.html" %}
	{% block content %}
		{{ table }}
	{% endblock content %}

app/templates/test_vertlayout.html
{% extends "layout.html" %}
	{% block content %}
		{{ table }}
		<!-- <script src="{{ url_for('static',filename='javascript/tableswapper.js') }}" defer="defer"></script> -->
	{% endblock content %}